project_id = "ptnfrvvihpbudjrlzzhn"

[functions.capture-screenshot]
verify_jwt = false

[functions.report-bot]
verify_jwt = false

[functions.serve-page]
verify_jwt = false

[functions.track-event]
verify_jwt = false

[functions.verify-domains-cron]
enabled = true
verify_jwt = true
import_map = "./functions/verify-domains-cron/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/verify-domains-cron/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/verify-domains-cron/*.html" ]
